@extends('layout')
@section('content')
<section class="container">
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
    <div>contact</div>
</section>
@stop